### ISSUE TITLE
Error trying to run the demo

### ISSUE THREAD

**Issue by florin05** [benorama/mfe-advanced-demo#1]
Hello

I am trying to run this demo.
After "npm install" I run

> nx run counter-mfe:serve 

Do I need to install some webpack new version or add-on separately?

Cannot find module 'webpack/lib/container/ModuleFederationPlugin'
Require stack:
- C:\dev\samples\mfe-advanced-demo\apps\counter-mfe\webpack.config.js
- C:\dev\samples\mfe-advanced-demo\node_modules\ngx-build-plus\src\utils\index.js
- C:\dev\samples\mfe-advanced-demo\node_modules\ngx-build-plus\src\plus-dev-server\index.js
- C:\dev\samples\mfe-advanced-demo\node_modules\@nrwl\tao\src\shared\workspace.js
- C:\dev\samples\mfe-advanced-demo\node_modules\@nrwl\tao\src\commands\run.js
- C:\dev\samples\mfe-advanced-demo\node_modules\@nrwl\tao\index.js
- C:\dev\samples\mfe-advanced-demo\node_modules\@nrwl\cli\lib\run-cli.js

**Comment by onilink128** [comment]
I running the application and don`t have any problem.
Don't you forget to change from npm to yarn?

**Comment by benorama** [comment]
Indeed you should try with Yarn.
Note: we are currently upgrading to Angular 12 RC1.
